/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityEvents {
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  properties: Generated<Json>;
  schema_version: string;
  subject_id: string | null;
  subject_type: string;
  user_id: string | null;
}

export interface AnalysisResults {
  analysis_run_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  result: Json;
  summary: string;
  updated_at: Generated<Timestamp>;
}

export interface AnalysisRuns {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  model_name: string | null;
  model_version: string | null;
  page_version_id: string;
  prompt_version: string;
  runner: string;
  schema_version: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Assets {
  byte_size: Int8;
  created_at: Generated<Timestamp>;
  height: number | null;
  id: Generated<string>;
  kind: string;
  mime_type: string;
  object_key: string;
  sha256: string;
  width: number | null;
}

export interface AuthIdentities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  provider: string;
  provider_subject: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface EmbeddingModels {
  created_at: Generated<Timestamp>;
  dimensions: number;
  id: Generated<string>;
  model_name: string;
  model_version: string;
  provider: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IngestionJobs {
  available_at: Generated<Timestamp>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_stage: string | null;
  id: Generated<string>;
  idempotency_key: string;
  input_url: string;
  last_error_code: string | null;
  last_error_summary: string | null;
  lease_expires_at: Timestamp | null;
  lease_owner: string | null;
  lease_token: string | null;
  normalized_url: string | null;
  page_id: string | null;
  page_version_id: string | null;
  retry_count: Generated<number>;
  started_at: Timestamp | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface JobAttempts {
  attempt_number: number;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  error_summary: string | null;
  id: Generated<string>;
  job_id: string;
  stage: string;
  started_at: Timestamp;
  status: string;
}

export interface PageLanguages {
  confidence: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  language_code: string;
  page_version_id: string;
  role: string;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface Pages {
  canonical_url: string;
  created_at: Generated<Timestamp>;
  current_version_id: string | null;
  discovery_source_url: string | null;
  id: Generated<string>;
  last_checked_at: Timestamp | null;
  normalized_url_hash: string;
  page_type_id: string | null;
  site_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PageTaxonomyTerms {
  confidence: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  page_version_id: string;
  source: string;
  term_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PageTypes {
  created_at: Generated<Timestamp>;
  display_order: number;
  id: Generated<string>;
  key: string;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PageUrls {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  normalized_url: string;
  page_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PageVersions {
  capture_profile_key: string;
  captured_at: Timestamp;
  content_fingerprint: string;
  created_at: Generated<Timestamp>;
  final_url: string;
  full_page_asset_id: string | null;
  id: Generated<string>;
  page_id: string;
  published_at: Timestamp | null;
  status: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  version_number: number;
  viewport_asset_id: string | null;
}

export interface PendingTaxonomyTerms {
  analysis_run_id: string;
  created_at: Generated<Timestamp>;
  group_key: string;
  id: Generated<string>;
  resolved_term_id: string | null;
  status: Generated<string>;
  suggested_name: string;
  updated_at: Generated<Timestamp>;
}

export interface SavedViews {
  created_at: Generated<Timestamp>;
  height: Generated<number>;
  id: Generated<string>;
  page_version_id: string;
  preview_asset_id: string | null;
  reason: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  width: Generated<number>;
  x: Generated<number>;
  y: Generated<number>;
}

export interface SavedViewTags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  saved_view_id: string;
  tag_id: string;
}

export interface SiteLanguages {
  confidence: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  language_code: string;
  role: string;
  site_id: string;
  source: string;
  updated_at: Generated<Timestamp>;
}

export interface Sites {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string | null;
  primary_industry_term_id: string | null;
  registrable_domain: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TaxonomyTerms {
  created_at: Generated<Timestamp>;
  display_order: number;
  group_key: string;
  id: Generated<string>;
  key: string;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface UserTags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  normalized_name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface VersionComparisons {
  baseline_page_version_id: string | null;
  candidate_asset_id: string;
  color_distance: number | null;
  created_at: Generated<Timestamp>;
  decision: string;
  id: Generated<string>;
  image_difference: number | null;
  layout_difference: number | null;
  page_id: string;
  perceptual_hash_distance: number | null;
  resulting_page_version_id: string | null;
  rule_version: string;
  text_difference: number | null;
}

export interface VisualEmbeddings {
  created_at: Generated<Timestamp>;
  embedding: string;
  id: Generated<string>;
  model_id: string;
  visual_region_id: string;
}

export interface VisualRegions {
  asset_id: string | null;
  created_at: Generated<Timestamp>;
  height: number;
  id: Generated<string>;
  kind: string;
  label: string | null;
  page_version_id: string;
  source: string;
  updated_at: Generated<Timestamp>;
  width: number;
  x: number;
  y: number;
}

export interface DB {
  activity_events: ActivityEvents;
  analysis_results: AnalysisResults;
  analysis_runs: AnalysisRuns;
  assets: Assets;
  auth_identities: AuthIdentities;
  embedding_models: EmbeddingModels;
  ingestion_jobs: IngestionJobs;
  job_attempts: JobAttempts;
  page_languages: PageLanguages;
  page_taxonomy_terms: PageTaxonomyTerms;
  page_types: PageTypes;
  page_urls: PageUrls;
  page_versions: PageVersions;
  pages: Pages;
  pending_taxonomy_terms: PendingTaxonomyTerms;
  saved_view_tags: SavedViewTags;
  saved_views: SavedViews;
  site_languages: SiteLanguages;
  sites: Sites;
  taxonomy_terms: TaxonomyTerms;
  user_tags: UserTags;
  users: Users;
  version_comparisons: VersionComparisons;
  visual_embeddings: VisualEmbeddings;
  visual_regions: VisualRegions;
}
